Build profiles and reproducible builds
arduino/tooling-rfcs pull request #5
Opened 2021-07-01 07:42 UTC by cmaglie

This RFC aims to propose new augmentations to the current library management and a build system that can be entirely transparent to the user and retains backward compatibility yet allowing more flexibility for the future.

2021-07-11 05:31 UTC, per1234 requested changes

2021-07-11 05:31 UTC, per1234 commented on RFCs/0003-build-profiles.md
> +- `<PROFILE*NAME>` is the profile identifier, it’s a user-defined field, and the allowed characters are alphanumerics, underscore `_`, dot `.`, and dash `-`
```suggestion
- `<PROFILE_NAME>` is the profile identifier, it’s a user-defined field, and the allowed characters are alphanumerics, underscore `_`, dot `.`, and dash `-`
```

2021-07-11 05:31 UTC, per1234 commented on RFCs/0003-build-profiles.md
> +A typical usage scenario is when the sketch needs a library that is not part of the library manager, or if the sketch needs a library with some customizations that are not available in the upstream r
```suggestion
A typical usage scenario is when the sketch needs a library that is not offered for installation from Library Manager, or if the sketch needs a library with some customizations that are not available in the upstream release.
```

2021-07-11 05:31 UTC, per1234 commented on RFCs/0003-build-profiles.md
> +To accomplish this the idea is to put the custom libraries' source code directly in the sketch `libraries` subdirectory (exactly as we do for the globally installed libraries in the `libraries` subdi
```suggestion
To accomplish this the idea is to put the custom libraries' source code directly in the `libraries` subdirectory of the sketch (exactly as we do for the globally installed libraries in the `libraries` subdirectory of the sketchbook root folder). For example:
```

2021-07-11 05:31 UTC, per1234 commented on RFCs/0003-build-profiles.md
> +Currently, Arduino guarantees no portability and reproducibility of a build at a later time unless exact instructions are provided by the developer to the final user, such as the required platform, i
```suggestion
Currently, the only way to guarantee portability and reproducibility of a sketch build at a later time is for the developer to provide instructions to the final user for the installation of the sketch dependencies, including the exact versions of the boards platform and libraries.
```
I think this wording makes the meaning slightly more clear.

2021-07-11 18:00 UTC, ladyada commented
Hi please add the ability to dynamically add -D define lines on the sketch compilation thru the yaml!

2021-07-13 10:38 UTC, cmaglie commented
> Hi please add the ability to dynamically add -D define lines on the sketch compilation thru the yaml!

Yep, we are going to add this feature later: we are keeping this version of the RFC as simple as possible so we can get it implemented ASAP and extend it later as we need.

(adding defines to profiles is tracked here: https://github.com/arduino/tooling-rfcs/issues/9)

2021-07-14 04:22 UTC, per1234 approved these changes

2021-08-16 13:24 UTC, merged